### ISSUE TITLE
Incompatible with Kotlin 2.3.20 — NoSuchMethodError in CancellationExceptionSubclassChecker

### ISSUE THREAD

**Issue by kdroidFilter** [santimattius/structured-coroutines#39]
## Description

The plugin crashes during compilation with Kotlin 2.3.20. The issue is in `CancellationExceptionSubclassChecker` which calls a FIR API method that no longer exists in this Kotlin version.

Works fine with Kotlin 2.3.10, crashes with 2.3.20.

The same issue occurs with plugin versions 0.4.0 and 0.5.0 — it is not specific to one plugin version.

## Error

```
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol 
  org.jetbrains.kotlin.fir.resolve.ToSymbolUtilsKt.toClassSymbol(
    org.jetbrains.kotlin.fir.SessionHolder, 
    org.jetbrains.kotlin.fir.types.ConeKotlinType, 
    org.jetbrains.kotlin.fir.FirSession)'
    at io.github.santimattius.structured.compiler.CancellationExceptionSubclassChecker.check(CancellationExceptionSubclassChecker.kt:86)
```

## Environment

- **Kotlin version**: 2.3.20 (works on 2.3.10)
- **Plugin version**: 0.5.0 (also reproduced with 0.4.0)
- **Build tool**: Gradle with Kotlin DSL

## Notes

The method signature for `toClassSymbol` in `org.jetbrains.kotlin.fir.resolve.ToSymbolUtilsKt` has changed in Kotlin 2.3.20, causing the `NoSuchMethodError`. It would be great to get compatibility with the latest Kotlin releases.

**Comment by kdroidFilter** [comment]
@santimattius It's work fine ! Awesome module ! Thanks you !
